# Generated by Django 3.0.6 on 2020-06-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20200602_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('habit', 'quantity')},
        ),
    ]
