# Generated by Django 3.0.6 on 2020-06-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20200602_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='recorded_on',
            field=models.DateField(auto_now=True),
        ),
    ]
