# Generated by Django 3.0.6 on 2020-06-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_dailyrecord_recorded_on'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('habit', 'recorded_on')},
        ),
    ]
