# Generated by Django 3.0.6 on 2020-06-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_auto_20200602_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='noun',
            new_name='unit_of_measure',
        ),
    ]
