# Generated by Django 3.0.6 on 2020-06-03 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_auto_20200603_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='verb',
            new_name='action',
        ),
    ]
