# Generated by Django 3.0.6 on 2020-06-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_auto_20200603_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='recorded_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
