# Generated by Django 3.0.6 on 2020-06-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_auto_20200608_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='recorded_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
